datacenter/urls.py
from django.urls import path
from datacenter import views

app_name = 'datacenter'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('course/', views.course, name='course')
]

java_ztm/urls.py
from django.contrib import admin
from django.urls import path, include
from datacenter import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('datacenter/', include('datacenter.urls')),
    path('logout/', views.user_logout, name='logout'),
]

datacenter/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileDetails(models.Model):

    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username

datacenter/forms.py
from django import forms
from django.contrib.auth.models import User
from datacenter.models import UserProfileDetails


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileDetailsForm(forms.ModelForm):
    class Meta():
        model = UserProfileDetails
        fields = ('portfolio_site', 'profile_pic')

datacenter/views.py
from django.shortcuts import render
from datacenter.forms import UserForm, UserProfileDetailsForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.

def index(request):
    return render(request, 'datacenter/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def course(request):
    return render(request, 'datacenter/course.html', {})


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileDetailsForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileDetailsForm()

    return render(request, 'datacenter/registration.html',
                    {'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request, 'datacenter/course.html', {})
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Login attempt failed")
            print("Username: <{}>, password: <{}>".format(username, password))
            return HttpResponse("Invalid login details provided.")
    else:
        return render(request, 'datacenter/login.html', {})

templates/datacenter/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {% block title %}
        <title></title>
        {% endblock %}
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'datacenter:register' %}">Register</a></li>
                
                    {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'datacenter:user_login' %}">Login</a></li>
                    {% endif %}
                
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/datacenter/course.html
<!DOCTYPE html>
{% extends 'datacenter/base.html' %}

{% block content %}

<div class = "jumbotron">
    <h1>HERE WILL BE JAVA COURSE</h1>
</div>

{% endblock %}

templates/datacenter/index.html
<!DOCTYPE html>
{% extends 'datacenter/base.html' %}

{% block content %}

<div class = "jumbotron">
    <h1>TEST - index.html</h1>
</div>

{% endblock %}

templates/datacenter/login.html
<!DOCTYPE html>
{% extends 'datacenter/base.html' %}
{% block content %}

<div class="jumbotron">
    <h1>Please Login - login.html</h1>
    <form action="{% url 'datacenter:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        
        <label for="password">Password:</label>
        <input type="password" name="password">
        
        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

templates/datacenter/registration.html
<!DOCTYPE html>
{% extends 'datacenter/base.html' %}
{% load static %}
{% block content %}

<div class = "jumbotron">
    {% if registered %}
        <h1>Thanks for being registered TEST - registration.html</h1>
    {% else %}
        <h1>GO TO SIGN-UP PAGE</h1>
        <h3>FILL FORM</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
        <input type="submit" name="" value="SIGN-UP">
        </form>
    {% endif %}
</div>
{% endblock %}